name: todo_list
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  connectivity: ^3.0.6
  http: ^1.2.2
  flutter_bloc: ^8.1.6
  get_it: ^8.0.3
  flutter_dotenv: ^5.2.1
  auto_route: ^9.3.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  build_runner:

flutter:
  uses-material-design: true
